apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-python-vapi-ffhl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-engineering-jech-tenant/devfile-sample-python-basic-vapi/demo-python-vapi-ffhl@sha256:e7880581644abfa78c11a0b9cc12bc6b5875226051dea886af484f3e6e2e36e2
        name: my-python
        resources: {}
status: {}
