apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-python-vapi-ffhl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-engineering-jech-tenant/devfile-sample-python-basic-vapi/demo-python-vapi-ffhl@sha256:bee5a4d0d34dca9b22b10e88d1ff9d2fdab0a0eccaee806ec52d790b03b387cc
        name: my-python
        resources: {}
status: {}
