apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-python-vapi-ffhl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-python-vapi-ffhl
    app.kubernetes.io/part-of: devfile-sample-python-basic-vapi
  name: demo-python-vapi-ffhl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: demo-python-vapi-ffhl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: demo-python-vapi-ffhl
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-engineering-jech-tenant/devfile-sample-python-basic-vapi/demo-python-vapi-ffhl@sha256:e7880581644abfa78c11a0b9cc12bc6b5875226051dea886af484f3e6e2e36e2
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
