apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo-python-vapi-ffhl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo-python-vapi-ffhl
    app.kubernetes.io/part-of: devfile-sample-python-basic-vapi
  name: demo-python-vapi-ffhl
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: demo-python-vapi-ffhl
status:
  loadBalancer: {}
